# Generated by Django 5.1.7 on 2025-03-12 09:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='posts_post_publish_d545fc_idx',
        ),
        migrations.AddField(
            model_name='post',
            name='image_height',
            field=models.IntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='image_width',
            field=models.IntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(height_field='image_height', help_text='Web-optimized image in JPEG/WebP format', upload_to='uploads/%Y/%m/%d/', width_field='image_width'),
        ),
        migrations.AlterField(
            model_name='post',
            name='intro',
            field=models.TextField(help_text='Brief summary for search engine snippets'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status', 'publish'], name='posts_post_status_71ebd0_idx'),
        ),
    ]
